name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate
      run: make generate

    - name: Build
      run: make clang test-targets

    - name: Run unit tests
      run: make test
